### ISSUE TITLE
Add support for metadata hash when sending transaction 

### ISSUE THREAD

**Issue by Imdavyking** [mrtnetwork/polkadot_dart#1]
An account must add mode and metadata_hash to transaction if  'CheckMetadataHash' in signed_extensions:
Mode is usually  'Disabled' and metadata hash is None

**Comment by Imdavyking** [comment]
payload_dict = {
            'call': call_data,
            'era': era,
            'nonce': nonce,
            'tip': tip,
            'spec_version': self.runtime_version,
            'genesis_hash': genesis_hash,
            'block_hash': block_hash,
            'transaction_version': self.transaction_version,
            'asset_id': {'tip': tip, 'asset_id': tip_asset_id},
            'metadata_hash': None,
            'mode': 'Disabled'
        }

**Comment by mrtnetwork** [comment]
> payload_dict = { 'call': call_data, 'era': era, 'nonce': nonce, 'tip': tip, 'spec_version': self.runtime_version, 'genesis_hash': genesis_hash, 'block_hash': block_hash, 'transaction_version': self.transaction_version, 'asset_id': {'tip': tip, 'asset_id': tip_asset_id}, 'metadata_hash': None, 'mode': 'Disabled' }

thanks for report that
